<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-29T17:52:18Z" name="Default suite" finished-at="2022-01-29T17:52:18Z" duration-ms="73">
    <groups>
      <group name="smoke">
        <method signature="Testing3.createUser()[pri:1, instance:testing.Testing3@352c1b98]" name="createUser" class="testing.Testing3"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2022-01-29T17:52:18Z" name="Default test" finished-at="2022-01-29T17:52:18Z" duration-ms="73">
      <class name="testing.Testing3">
        <test-method signature="createUser()[pri:1, instance:testing.Testing3@352c1b98]" started-at="2022-01-29T17:52:18Z" name="createUser" finished-at="2022-01-29T17:52:18Z" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method signature="editUser()[pri:2, instance:testing.Testing3@352c1b98]" started-at="2022-01-29T17:52:18Z" name="editUser" finished-at="2022-01-29T17:52:18Z" depends-on-methods="testing.Testing3.createUser" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editUser -->
        <test-method signature="deleteUser()[pri:3, instance:testing.Testing3@352c1b98]" started-at="2022-01-29T17:52:18Z" name="deleteUser" finished-at="2022-01-29T17:52:18Z" depends-on-methods="testing.Testing3.editUser" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verifying Element expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verifying Element expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testing.Testing3.deleteUser(Testing3.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- testing.Testing3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
